version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.8
    steps:
      - checkout

      - run:
          name: Show Repo Structure
          command: |
            pwd
            ls -la
            echo "---- Backend ----"
            ls -la Backend

      - restore_cache:
          keys:
            - node-deps-{{ checksum "Backend/package-lock.json" }}
            - node-deps-

      - run:
          name: Install Dependencies (with verbose logging)
          command: |
            cd Backend
            npm ci --verbose || npm install --verbose

      - save_cache:
          key: node-deps-{{ checksum "Backend/package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run ESLint
          command: cd Backend && npx eslint . --ext .js,.jsx,.ts,.tsx || true

      - run:
          name: Run Jest Tests
          command: cd Backend && npm test -- --ci --reporters=default

workflows:
  version: 2
  ci-pipeline:
    jobs:
      - build-and-test
