version: 2.1

jobs:
  build-and-run:
    docker:
      - image: cimg/node:22.8  # Node.js Docker image
    steps:
      - checkout  # Checkout your code

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            npm ci

      # Start the application
      - run:
          name: Start Application
          command: |
            npm run start

workflows:
  version: 2
  trigger_pipeline:
    jobs:
      - build-and-run
