version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Add your other envs here, or use an .env file
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on: []